// <auto-generated />
using System;
using MetallurgyAnalytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRP_MRP_Planning_Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MetallurgyAnalytics.Models.BillOfMaterials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("bill_of_materials");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.BomLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomId")
                        .HasColumnType("integer")
                        .HasColumnName("bom_id");

                    b.Property<int>("ComponentProductId")
                        .HasColumnType("integer")
                        .HasColumnName("component_product_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("ComponentProductId");

                    b.ToTable("bom_lines");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.Formula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ConsumptionCoeff")
                        .HasColumnType("double precision")
                        .HasColumnName("consumption_coeff");

                    b.Property<int>("EndProductId")
                        .HasColumnType("integer")
                        .HasColumnName("end_product_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer")
                        .HasColumnName("ingredient_id");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("work_center_id");

                    b.HasKey("Id");

                    b.HasIndex("EndProductId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("formulas");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Bmax")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("bmax");

                    b.Property<decimal>("Bmin")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("bmin");

                    b.Property<decimal>("Hmax")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hmax");

                    b.Property<decimal>("Hmin")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("hmin");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pozitsiya");

                    b.Property<string>("Preform")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("zagotovka");

                    b.Property<decimal>("SteelGradeGroup")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("gruppamarokstali");

                    b.HasKey("Id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("HeightMm")
                        .HasColumnType("numeric")
                        .HasColumnName("height_mm");

                    b.Property<int>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PreformType")
                        .HasColumnType("text")
                        .HasColumnName("preform_type");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("uom");

                    b.Property<decimal?>("WidthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("width_mm");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.ProductPositionLink", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("products_id");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("positions_id");

                    b.HasKey("ProductId", "PositionId");

                    b.HasIndex("PositionId");

                    b.ToTable("product_positions");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("DateFinishPlanned")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_finish_planned");

                    b.Property<DateTime>("DateStartPlanned")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start_planned");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("production_orders");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("material_task");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.StockMove", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateExpected")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_expected");

                    b.Property<string>("MoveType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("production_order_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision")
                        .HasColumnName("quantity");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("stock_moves");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.WorkCenter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacityPerHour")
                        .HasColumnType("double precision")
                        .HasColumnName("capacity_per_hour");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<double>("CostPerHour")
                        .HasColumnType("double precision")
                        .HasColumnName("cost_per_hour");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<double>("RollingSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("rolling_speed");

                    b.HasKey("Id");

                    b.ToTable("work_centers");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEndPlanned")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end_planned");

                    b.Property<DateTime>("DateStartPlanned")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start_planned");

                    b.Property<double>("DurationExpectedHours")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_expected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer")
                        .HasColumnName("position_id");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("production_order_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("integer")
                        .HasColumnName("work_center_id");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("work_orders");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.BillOfMaterials", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.Product", "Product")
                        .WithMany("BomVersions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.BomLine", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.BillOfMaterials", "Bom")
                        .WithMany("Lines")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.Product", "ComponentProduct")
                        .WithMany()
                        .HasForeignKey("ComponentProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");

                    b.Navigation("ComponentProduct");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.Formula", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.Position", "EndProduct")
                        .WithMany()
                        .HasForeignKey("EndProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.Position", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndProduct");

                    b.Navigation("Ingredient");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.ProductPositionLink", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.Position", "Position")
                        .WithMany("ProductPositionLinks")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.Product", "Product")
                        .WithMany("ProductPositionLinks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.ProductionOrder", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.User", "CreatedByUser")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("MetallurgyAnalytics.Models.Product", "Product")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.StockMove", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.Product", "Product")
                        .WithMany("StockMoves")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId");

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.WorkOrder", b =>
                {
                    b.HasOne("MetallurgyAnalytics.Models.Position", "Position")
                        .WithMany("WorkOrders")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.ProductionOrder", "ProductionOrder")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MetallurgyAnalytics.Models.WorkCenter", "WorkCenter")
                        .WithMany("WorkOrders")
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("ProductionOrder");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.BillOfMaterials", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.Position", b =>
                {
                    b.Navigation("ProductPositionLinks");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.Product", b =>
                {
                    b.Navigation("BomVersions");

                    b.Navigation("ProductPositionLinks");

                    b.Navigation("ProductionOrders");

                    b.Navigation("StockMoves");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.ProductionOrder", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.User", b =>
                {
                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("MetallurgyAnalytics.Models.WorkCenter", b =>
                {
                    b.Navigation("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
