pipeline {
	agent any
	
	stages {
		stage('Hello') {
			steps {
				echo 'Hello jenkins from Nerio!'
			}
		}
		stage('Build Docker Image') {
			steps {
				dir(MRP_CRP_Planning_System-master_3/MRP_CRP_Planning_System-master) {
					sh 'ls -l'
					sh 'docker compose build'
				}
			}
		}
		stage('Start Docker Container') {
			steps {
				dir(MRP_CRP_Planning_System-master_3/MRP_CRP_Planning_System-master) {
					sh 'docker compose up -d'
			}
		}
	}
}
