name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Listar archivos para comprobar
      run: ls -la
    - name: Build the Docker image
      run: docker compose -f docker-compose.yml build
    - name: Save the Docker image
      run: docker save crp_mrp_planning_image > docker-image.tar
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        name: docker-image.tar
        path: docker-image.tar
