name: Docker Image CI
on:
  push:
    branches: [ "master", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Descargar el codigo
      uses: actions/checkout@v4
      
    - name: 2. Construir la imagen
      run: |
        cd MRP_CRP_Planning_System-master
        docker build -f Dockerfile -t crp_mrp_planning_image .
        
    - name: 3. Guardar la imagen
      run: |
        cd MRP_CRP_Planning_System-master
        docker save crp_mrp_planning_image > docker-image.tar
        
    - name: 4. Subir el artefacto
      uses: actions/upload-artifact@v5.0.0
      with:
        name: docker-image.tar
        path: MRP_CRP_Planning_System-master/docker-image.tar
